[package]
name = "rand_race"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.1"
csv = "1.3.0"
rand = "0.8.5"
